### ISSUE TITLE
Ksnap stopped consuming messages from topics prematurely when connecting to a kafka broker with slow connection

### ISSUE THREAD

**Issue by alex817** [EclipseTrading/ksnap#13]
There is a mechanism where ksnap reader waits for messages and exit if there is no new messages after x secs. This serves the purpose of consuming all messages and exit the consuming stage if ksnap has a good and fast connection with target kafka cluster.

I think we should get the latest offsets of all topics and wait until we receive messages with said offsets then exit along with a generous consumer timeout.

**Comment by akamensky** [comment]
> I think we should get the latest offsets of all topics and wait until we receive messages with said offsets then exit along with a generous consumer timeout.

That is how it was implemented in 1.x with Go (regardless of the bug that prompted switch to Python). It should:

1. Get current partition offset
2. Read data until that offset is reached
3. If cannot reach that offset (or any other error), entire process should exit with error code (i.e. 1) to signal a problem

**Comment by alex817** [comment]
@akamensky Agreed. v2.0.2 includes the change you suggested above.
